---
name: publish

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]"

permissions:
  # This permission is required for trusted publishing.
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up python 3.11
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up Poetry
        uses: ./.github/actions/setup-poetry
        with:
          groups: main
          python-version: "3.11"

      - name: Update version (kept at 0.0.0) in pyproject.toml and build
        run: |
          # Remove v prefix from tag
          export VERSION=(echo ${{ github.ref_name}} | sed 's/^v//')
          poetry version $VERSION
          poetry build

      - name: Mint token
        id: mint
        uses: tschm/token-mint-action@v1.0.2

      - name: Publish the package with poetry
        run: |
          poetry publish -u __token__ -p '${{ steps.mint.outputs.api-token }}'
